################################################################
## Autor: Bräker, Dietrich, Meyer, Zaugg
## Version 5.0
################################################################

Vagrant.configure("2") do |config|

	#Erster Server, Webserver
	config.vm.define "srv01_lx_webserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			
			vb.name = "srv01_lx_webserver"
			vb.memory = "512"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv01-lx-webserver"
		subconfig.vm.network :private_network, ip: "10.0.0.10"
		subconfig.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

		#Shell für den Webserver 
		subconfig.vm.provision "shell", inline: <<-SHELL

			#Diverse Services installieren
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#Wordpress installieren
			cd /var/www/html
			sudo wget -c http://wordpress.org/latest.tar.gz
			sudo tar -xzvf latest.tar.gz
			sudo rsync -av wordpress/* /var/www/html/
			sudo chown -R www-data:www-data /var/www/html/
			sudo chmod -R 755 /var/www/html/
			#sudo mv wp-config-sample.php wp-config.php

			#Neustarten
			sudo reboot
		SHELL
	end

	#Zweiter Server, Datenbankserver
	config.vm.define "srv02_lx_databaseserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			vb.name = "srv02_lx_databaseserver"
			vb.memory = "512"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv02-lx-databaseserver"
		subconfig.vm.network :private_network, ip: "10.0.0.11"

		#Shell srv02
		subconfig.vm.provision "shell", inline: <<-SHELL
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#UFW Konfigurieren
			sudo ufw enable
			sudo ufw allow from 10.0.0.10 to any port 3306 #Remote Server darf auf Mysql zugreiffen
			sudo systemctl start mysql
			sudo systemctt start ufw


			#Erstellen der Datenbank und dem User für den srv01
			mysql -uroot -padmin -e "CREATE DATABASE db_wordpress;"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin'@'10.0.0.11' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin1'@'%' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "FLUSH PRIVILEGES;"
			sudo systemctl restart mysql
			#Neustarten, damit alle Services neu gestartet werden
			sudo reboot
		SHELL
	end
  
  #Reverse Proxy Server
  #Grundkonfiguration der VM
  config.vm.define "srv05-lx-proxy" do |subconfig|
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "srv05-lx-proxy"
      vb.memory = "512"
    end

  subconfig.vm.box = "ubuntu/xenial64"
	subconfig.vm.hostname = "srv05-lx-proxy"
	subconfig.vm.network :private_network, ip: "10.0.0.14"
	subconfig.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  
  #Shell für den Proxy Server
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    #Installation apache
    sudo apt-get -y install apache2 libxml2-dev
    #Reverse Proxy
    sudo a2enmod proxy
	sudo a2enmod proxy_html
	sudo a2enmod proxy_http
    #kopieren und verlinken der reverse proxy config datei
    sudo cp /vagrant/001-reverseproxy.conf /etc/apache2/sites-available/
    sudo ln -s /etc/apache2/sites-available/001-reverseproxy.conf /etc/apache2/sites-enabled/
    #Neustart der Dienste
    sudo service apache2 restart
    #Firewall regeln erstellen und Firewall aktivieren
    sudo ufw allow 80/tcp
    sudo ufw allow 22/tcp
    sudo ufw -f enable

   SHELL
  end
  
  #Fileserver
	#Grundkonfigurationen für die VM
	config.vm.define "srv03-lx-fileserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			vb.name = "srv03-lx-fileserver"
			vb.memory = "512"
	  end

	subconfig.vm.box = "ubuntu/trusty64"
 	subconfig.vm.hostname = "srv03-lx-fileserver"
	subconfig.vm.network :private_network, ip: "10.0.0.12"
	
	#Shell für den Fileserver 
	subconfig.vm.provision "shell", inline: <<-SHELL
	#Diverse Services installieren
		set -o xtrace
		sudo apt-get update
        sudo apt-get -y install samba-common samba 
		sudo apt-get -y install tdb-tools 
	#Service Konfigurieren SAMBA 
		sudo su
	#smb.conf anpassen 
		sudo echo " server min protocol = SMB2_02 
		server max protocol = SMB3" >> /etc/samba/smb.conf
		sudo echo "guest ok = yes" >> /etc/samba/smb.conf
		sudo echo "usershare allow guests = yes" >> /etc/samba/smb.conf
		sudo echo "map to guest = bad user" >> /etc/samba/smb.conf
		sudo echo "guest account = nobody" >> /etc/samba/smb.conf
		sudo echo "writeable = yes" >> /etc/samba/smb.conf
		sudo echo "comment= Samaba 
		path= /home/sambashare
		read only = no 
		browsable = yes" >> /etc/samba/smb.conf
	#Share Folder erstellen 
		sudo mkdir /home/sambashare
	#Service Neustarten
		sudo service smbd restart			
	#Firewallrule aktualisieren
        sudo ufw allow samba
	#Backup Installieren
		sudo apt-get update
		sudo apt-get -y install rsync 
		#Backup einrichten Ziel zum Backup Server 
		sudo rsync -a /home/sambashare /srv04_lx_fileserver
        SHELL
	end
	
	#Zweiter Server, Backupserver
		config.vm.define "srv04-lx-fileserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			vb.name = "srv04-lx-fileserver"
			vb.memory = "512"
		end

		subconfig.vm.box = "ubuntu/trusty64"
		subconfig.vm.hostname = "srv04-lx-fileserver"
		subconfig.vm.network :private_network, ip: "10.0.0.13"

	#Shell srv04
		subconfig.vm.provision "shell", inline: <<-SHELL
			#Creat Folder for Backup from Fileserver
			sudo mkdir /home/backup
		
		SHELL
	end
end