Vagrant.configure("2") do |config|

	#Erster Server, Webserver
	config.vm.define "srv01_lx_webserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			
			vb.name = "srv01_lx_webserver"
			vb.memory = "1024"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv01-lx-webserver"
		subconfig.vm.network :private_network, ip: "10.0.0.10"
		subconfig.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

		#Shell für den Webserver 
		subconfig.vm.provision "shell", inline: <<-SHELL

			#Diverse Services installieren
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#Wordpress installieren
			cd /var/www/html
			sudo wget -c http://wordpress.org/latest.tar.gz
			sudo tar -xzvf latest.tar.gz
			sudo rsync -av wordpress/* /var/www/html/
			sudo chown -R www-data:www-data /var/www/html/
			sudo chmod -R 755 /var/www/html/
			sudo mv wp-config-sample.php wp-config.php
			#Wordpress ist jetzt unter localhost:8080/wordpress erreichbar

			#Neustarten, damit alle Services neu gestartet werden
			sudo reboot
		SHELL
	end

	#Zweiter Server, Datenbankserver
	config.vm.define "srv02_lx_databaseserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			vb.name = "srv02_lx_databaseserver"
			vb.memory = "512"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv02-lx-databaseserver"
		subconfig.vm.network :private_network, ip: "10.0.0.11"

		#Shell srv02
		subconfig.vm.provision "shell", inline: <<-SHELL
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#UFW Konfigurieren
			sudo ufw disable
			#sudo ufw enable
			#sudo ufw allow mysql
			sudo systemctl start mysql

			#Erstellen der Datenbank und dem User für den srv01
			mysql -uroot -padmin -e "CREATE DATABASE db_wordpress;"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin'@'10.0.0.11' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin1'@'%' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "FLUSH PRIVILEGES;"
			#sudo su
			#sudo echo 'bind-address = 10.0.0.10' >> /etc/mysql/mysql.conf.d/mysqld.cnf
			#exit
			sudo systemctl restart mysql
			#Neustarten, damit alle Services neu gestartet werden
			sudo reboot

		SHELL
	end
	#config.vm.provision "shell", inline: <<-SHELL 
	#Konfig für alle Virtuellen Maschienen
	#SHELL
end