#To do
#srv01: Konfigfile wird nicht richtig eingelesen
#srv02 man im mysql dort bei bind-adress 0.0.0.0
#sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf

Vagrant.configure("2") do |config|

	#Erster Server, Webserver
	config.vm.define "srv01_lx_webserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			
			vb.name = "srv01_lx_webserver"
			vb.memory = "1024"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv01-lx-webserver"
		subconfig.vm.network :private_network, ip: "10.0.0.10"
		subconfig.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

		#Shell für den Webserver 
		subconfig.vm.provision "shell", inline: <<-SHELL

			#Diverse Services installieren
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#Wordpress installieren
			cd /var/www/html
			sudo wget -c http://wordpress.org/latest.tar.gz
			sudo tar -xzvf latest.tar.gz
			sudo rsync -av wordpress/* /var/www/html/
			sudo chown -R www-data:www-data /var/www/html/
			sudo chmod -R 755 /var/www/html/
			sudo mv wp-config-sample.php wp-config.php

			#Wordpress konfigurieren
			sudo nano > /var/www/html/wp-config.php
			sudo su
			echo '<?php' >> /var/www/html/wp-config.php
			echo 'define(‘DB_NAME’, ‘wordpress’);' >> /var/www/html/wp-config.php
			echo 'define(‘DB_USER’, ‘webadmin1’);' >> /var/www/html/wp-config.php
			echo 'define(‘DB_PASSWORD’, ‘1234’);' >> /var/www/html/wp-config.php
			echo "define(‘DB_HOST’, ‘10.0.0.11:3306’);" >> /var/www/html/wp-config.php
			echo "define(‘DB_CHARSET’, ‘utf8′);" >> /var/www/html/wp-config.php
			echo "define(‘DB_COLLATE’, ”);" >> /var/www/html/wp-config.php
			echo "define(‘AUTH_KEY’,         ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘SECURE_AUTH_KEY’,  ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘LOGGED_IN_KEY’,    ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘NONCE_KEY’,        ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘AUTH_SALT’,        ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘SECURE_AUTH_SALT’, ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘LOGGED_IN_SALT’,   ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "define(‘NONCE_SALT’,       ‘put your unique phrase here’);" >> /var/www/html/wp-config.php
			echo "$table_prefix  = ‘wp_’;" >> /var/www/html/wp-config.php
			echo "define(‘WPLANG’, ”);" >> /var/www/html/wp-config.php
			echo "define(‘WP_DEBUG’, false);" >> /var/www/html/wp-config.php
			echo "if ( !defined(‘ABSPATH’) )" >> /var/www/html/wp-config.php
			echo "define(‘ABSPATH’, dirname(__FILE__) . ‘/’);" >> /var/www/html/wp-config.php
			echo "require_once(ABSPATH . ‘wp-settings.php’);" >> /var/www/html/wp-config.php
			echo "?>" >> /var/www/html/wp-config.php
			
#Ende des Konfigfiles
			#Wordpress ist jetzt unter localhost:8080/wordpress erreichbar
			#Neustarten, damit alle Services neu gestartet werden
			sudo reboot
		SHELL
	end

	#Zweiter Server, Datenbankserver
	config.vm.define "srv02_lx_databaseserver" do |subconfig|
		subconfig.vm.provider "virtualbox" do |vb|
			vb.name = "srv02_lx_databaseserver"
			vb.memory = "512"
		end

		subconfig.vm.box = "ubuntu/xenial64"
		subconfig.vm.hostname = "srv02-lx-databaseserver"
		subconfig.vm.network :private_network, ip: "10.0.0.11"

		#Shell srv02
		subconfig.vm.provision "shell", inline: <<-SHELL
			set -o xtrace
			sudo apt-get update
			sudo apt-get -y upgrade
			sudo apt-get -y dist-upgrade
			sudo apt-get -y install debconf-utils 
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
			sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server

			#UFW Konfigurieren
			sudo ufw enable
			#sudo ufw allow mysql
			sudo ufw allow from 10.0.0.10 to any port 3306 #Remote Server darf auf Mysql zugreiffen
			sudo systemctl start mysql


			#Erstellen der Datenbank und dem User für den srv01
			mysql -uroot -padmin -e "CREATE DATABASE db_wordpress;"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin'@'10.0.0.11' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin1'@'%' IDENTIFIED BY '1234';"
			mysql -uroot -padmin -e "FLUSH PRIVILEGES;"
			#sudo su
			#sudo echo 'bind-address = 10.0.0.10' >> /etc/mysql/mysql.conf.d/mysqld.cnf
			#exit
			sudo systemctl restart mysql
			#Neustarten, damit alle Services neu gestartet werden
			sudo reboot
		SHELL
	end
end