Vagrant.configure(2) do |config|
	#Konfiguration von der Virtuellen Maschiene
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" 
	vb.name ="SVR01_lx_Webserver_withCMS"
end
config.vm.provision "shell", inline: <<-SHELL 
	
	#Installation von Applikationen
    set -o xtrace
	sudo apt-get update
	sudo apt-get -y install debconf-utils 
	sudo apt-get -y install apache2
	sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin' #Konfiguration mySQL (Passwort für root von mySQL)
	sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin' #Passwort bestätigen
	sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server
	sudo apt-get install wordpress
	
	#Erstellen der Datenbank und dem User
	mysql -uroot -padmin -e "CREATE DATABASE db_wordpress;"
	mysql -uroot -padmin -e "GRANT ALL PRIVILEGES ON db_wordpress.* TO 'webadmin'@'%' IDENTIFIED BY '1234';"
	mysql -uroot -padmin -e "FLUSH PRIVILEGES;"

	#Wordpress installieren
	cd /var/www/html
	sudo wget -c http://wordpress.org/latest.tar.gz
	sudo tar -xzvf latest.tar.gz
	sudo rsync -av wordpress/* /var/www/html/
	sudo chown -R www-data:www-data /var/www/html/
	sudo chmod -R 755 /var/www/html/
	sudo mv wp-config-sample.php wp-config.php

	#Alle Services neu starten
	sudo systemctl restart apache2.service 
	sudo systemctl restart mysql.service

SHELL
end
